# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 09:27
from __future__ import unicode_literals

import app_name.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bleep',
            name='content',
            field=models.CharField(max_length=140, validators=[app_name.validators.validate_content]),
        ),
    ]
