# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0002_auto_20170131_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bleep',
            options={'ordering': ['-timestamp']},
        ),
    ]
