# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0003_auto_20170202_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='bleep',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_name.Bleep'),
        ),
    ]
